apiVersion: v1
kind: Pod

metadata:
  labels:
    app: kaniko-agent

spec:
  serviceAccountName: jenkins

  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      tty: true
      command:
        - /busybox/cat

      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker

  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret
        items:
          - key: .dockerconfigjson
            path: config.json
